name: CI_Demo

on:
    push

jobs:
    build:
      name : build
      runs-on: ubuntu-latest
      steps:
        - name: checkout Repository
          uses: actions/checkout@v4

        - name: install Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - uses: iterative/setup-cml@v2
          
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements_dev.txt
        - name: Run python file
          run:  python run_pipeline.py
